If ThisDoc.Document.SubType = "{E60F81E1-49B3-11D0-93C3-7E0706000000}" Then
    ' Montagem principal
    Dim ass As AssemblyDocument = ThisDoc.Document
    Dim j As Integer
    Dim i As Integer

    ' Limpeza de iProperties da montagem principal
    For i = 1 To ass.PropertySets.Count
        If ass.PropertySets.Item(i).Name = "Design Tracking Properties" Or ass.PropertySets.Item(i).Name = "Inventor Summary Information" Or ass.PropertySets.Item(i).Name = "Inventor Document Summary Information" Then
            For j = 1 To ass.PropertySets.Item(i).Count
                Try
                    ass.PropertySets.Item(i).Item(j).Value = ""
                Catch
                End Try
            Next
        End If
    Next

    ' Limpeza de iProperties das peças e submontagens
    Dim doc As Document
    For Each doc In ass.AllReferencedDocuments
        ' Verifica se o documento é uma peça ou submontagem
        If doc.DocumentType = DocumentTypeEnum.kPartDocumentObject Or doc.DocumentType = DocumentTypeEnum.kAssemblyDocumentObject Then
            For i = 1 To doc.PropertySets.Count
                If doc.PropertySets.Item(i).Name = "Design Tracking Properties" Or doc.PropertySets.Item(i).Name = "Inventor Summary Information" Or doc.PropertySets.Item(i).Name = "Inventor Document Summary Information" Then
                    For j = 1 To doc.PropertySets.Item(i).Count
                        Try
                            doc.PropertySets.Item(i).Item(j).Value = ""
                        Catch
                        End Try
                    Next
                End If
            Next
        End If
    Next
ElseIf ThisDoc.Document.SubType <> "{E60F81E1-49B3-11D0-93C3-7E0706000000}" Then
    ' Limpeza de iProperties em documentos não de montagem
    For i = 1 To ThisDoc.Document.PropertySets.Count
        If ThisDoc.Document.PropertySets.Item(i).Name = "Design Tracking Properties" Or ThisDoc.Document.PropertySets.Item(i).Name = "Inventor Summary Information" Or ThisDoc.Document.PropertySets.Item(i).Name = "Inventor Document Summary Information" Then
            For j = 1 To ThisDoc.Document.PropertySets.Item(i).Count
                Try
                    ThisDoc.Document.PropertySets.Item(i).Item(j).Value = ""
                Catch
                End Try
            Next
        End If
    Next
End If
